title: Luis Rozo
subtitle: Software Engineer
description: Personal website of Luis Rozo.

author: Luis Rozo
email: luisgonzagarozo@gmail.com
avatar: assets/images/avatar.png

baseurl: ""
url: "https://luisrozo.github.io"

# Social settings
#facebook_url: https://www.facebook.com/chris.bobbe
github_url: https://github.com/luisrozo
linkedin_url: https://www.linkedin.com/in/luis-gonzaga-rozo-bueno-0299b7166/
twitter_url: https://twitter.com/luisrozo96

# SEO settiongs
#google_analytics: UA-112211352-1

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
